AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  assignment2lf2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search_photos_test
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./search_photos
      Description: 'Lambda function for smart-photos-album searching photos'
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::725740804677:role/service-role/search_photos-role-1tri1388'
      Environment:
        Variables:
          REGION: us-east-1

  assignment2lf1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index_photos2
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./assignment2_lf1
      Description: 'Lambda function for smart-photos-album indexing photos'
      MemorySize: 128
      Timeout: 120
      Role: 'arn:aws:iam::725740804677:role/service-role/assignment2_lf1-role-fyo0v0bh'
      Environment:
        Variables:
          REGION: us-east-1
    Bucket1:
      Type: 'AWS::S3::Bucket'
